server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com     #eureka服务端的实例名称, 映射到127.0.0.1, 修改hosts文件
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责就是维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    单机版
      defaultZone: http://eureka7001.com:7001/eureka/     #集群版，多个eureka服务器之间相互注册，相互守望，这里的地址写eureka7001.com的注册地址