server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848   #配置Nacos地址  单机版
         server-addr: nacos.com:80   #配置Nacos地址  集群版

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'