#服务端口号
server:
  port: 80

#服务名
spring:
  application:
    name: cloud-consumerzk-order
  cloud:
    zookeeper:
      connect-string: 192.168.20.125:2181,192.168.20.125:2182,192.168.20.125:2183    #zookeeper注册地址，集群版
