server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com:80   #nacos注册中心地址  集群版

#服务提供者注册到nacos的服务名称，供消费者访问
service-url:
  nacos-user-service: http://nacos-payment-provider




